name: Deploy to Pinata

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 依存関係をインストール
        run: npm install

      - name: フォルダをPinataにアップロード
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
        run: node uploadFolder.mjs
